# .github/workflows/update-data.yml
name: Update anime spots JSON

on:
  workflow_dispatch:      # 手動実行もできる
  schedule:
    - cron: '0 0 * * 1'   # 毎週月曜 00:00 UTC

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # --- Python セットアップ & 依存インストール ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      # --- スクレイパー実行 ---
      - name: Run scrape.py
        env:
          GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}
        run: |
          python scripts/scrape.py

      # --- 変更があれば commit & push ---
      - name: Commit & push
        run: |
          if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/places.json
            git commit -m "chore: weekly spot data update [skip ci]"
            git push origin ${{ github.ref }}
          fi
